# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f80c112c437128c4ad2167d4f6b274de762774b8f37b58873cad4a64ff5d865ffe2f93df74700ae3d1aef581786db8faa4b7a09f7e29be4ea1bd68f5f15f202

test:
  secret_key_base: 131ac20d5e7eee5ecd090b6c64ace4d9e501af57522dd97be9e697e8092008b78a8de2362a2ea269ee9deaa5049a8a31beec737fc6823ea08ccf3c203a62a71b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
